[theme]

# Theme - "light" or "dark"
base = "dark"

# Primary accent color - for buttons, sliders, etc.
primaryColor = "rgb(197, 44, 95)"

# Color used for all links.
linkColor = "rgb(197, 44, 95)"

# Background and secondary color of the app
backgroundColor = "rgb(38, 39, 48)"
secondaryBackgroundColor = "rgb(60, 62, 76)"  # For most interactive widgets

# Text, fonts, etc.
textColor = "#FFFFFF"
font = "sans serif"  # "sans serif", "serif", or "monospace"

showWidgetBorder = true

[theme.sidebar]
backgroundColor = "rgb(38, 39, 48)"
secondaryBackgroundColor = "rgb(60, 62, 76)"